name: Update Knowledgebase

on:
  schedule:
    - cron: "0 9 * * *"   # every day at 9am UTC
  workflow_dispatch:       # allow manual runs

jobs:
  update-kb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run update script
        env:
          RAINDROP_ACCESS_TOKEN: ${{ secrets.RAINDROP_ACCESS_TOKEN }}
          RAINDROP_REFRESH_TOKEN: ${{ secrets.RAINDROP_REFRESH_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}   # for enrichment
        run: |
          python .github/scripts/update_kb.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add knowledge.json digests/
          git commit -m "KB auto-update: $(date -u)"
          git push
