name: Update Knowledgebase

on:
  schedule:
    - cron: "0 9 * * *"   # every day at 9am UTC
  workflow_dispatch:       # allow manual runs

permissions:
  contents: write    # ✅ allow pushing commits

jobs:
  update-kb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ use built-in token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run update script
        env:
          RAINDROP_ACCESS_TOKEN: ${{ secrets.RAINDROP_ACCESS_TOKEN }}
          RAINDROP_REFRESH_TOKEN: ${{ secrets.RAINDROP_REFRESH_TOKEN }}
        run: |
          python .github/scripts/update_kb.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add knowledge.json digests/ || true
          git diff --cached --quiet || git commit -m "KB auto-update: $(date -u)"
          git push
